export enum QueueType {
  FAST = 'FAST',
  STANDARD = 'STANDARD'
}

export type DynamicWords = {
  Fair_Short_Name: string;
  Requester_name: string;
  Requester_company_name: string;
  Responder_company_name: string;
  Exhibitor_name: string;
  Buyer_name: string;
  Exhibitor_company_name: string;
  Buyer_company_name: string;
  Fair_long_name_EN: string;
  Fair_long_name_TC: string;
  Fair_long_name_SC: string;
  Responder_name: string;
  Meeting_date: string;
  Meeting_time: string;
  Cancel_Original_Meeting_hour: string;
  Link_PendingAccept: string;
  Link_Cancel: string;
  Link_Upcoming: string;

  Meeting_type_En: string;
  userName: string;
  meetingType: string;

  selfName: string;
  selfType: string;
  selfCompanyName: string;
  selfCountry: string;

  counterName: string;
  counterType: string;
  counterCompanyName: string;
  counterCountryEn: string;
  counterCountry: string;

  currentDate: string;
  selfTimeZone: string;
};

export enum NotificationTemplatesId {
  C2M_KICK_OFF_BUYER = 2,
  C2M_KICK_OFF_EXHIBITOR = 3,
  CREATE_MEETING = 6,
  RESCHEDULE_MEETING = 7,
  ACCEPT_MEETING_TO_REQUESTER = 8,
  ACCEPT_MEETING_TO_RESPONDER = 9,
  REJECT_MEETING = 10,
  CANCEL_MEETING = 11,
  AUTO_CANCEL_MEETING = 12,
  BM_CREATE_MEETING_NO_PENDING_MEETING_TO_BUYER = 13,
  BM_CREATE_MEETING_NO_PENDING_MEETING_TO_EXHIBITOR = 14,
  BM_CREATE_MEETING_WITH_PENDING_MEETING_TO_BUYER = 15,
  BM_CREATE_MEETING_WITH_PENDING_MEETING_TO_EXHIBITOR = 16,
  RESCHEDULE_BM_MEETING_BY_BUYER_OR_EXHIBITOR = 17,
  CANCEL_BM_MEETING_BY_BUYER_OR_EXHIBITOR = 24,
  CANCEL_BM_MEETING_BY_BM_TO_RESPONDER = 18,
  CANCEL_BM_MEETING_BY_BM_TO_REQUESTER = 23,
  CANCEL_C2M_MEETING_BY_BM_TO_REQUESTER = 22,
  CANCEL_C2M_MEETING_BY_BM_TO_RESPONDER = 25,
  DAILY_MEETING_SUMMARY = 19,
  MEETING_REMINDER = 20,
  C2M_START_REMINDER = 21,
  SEMINAR_REGISTRATION_SUCCESS = 30,
  SEMINAR_SUMMARY_REMINDER = 31,
  SEMINAR_ATTENDING_REMINDER = 32,
  FEEDBACK_FORM_REMINDER = 39,
  PLAYBACK_VIDEO_REMINDER = 38,
  NEW_BM_LIST = 33,
  UPDATED_BM_LIST = 34,
  NO_RESPONSE_REMINDER = 35,
  NOT_ENOUGH_INTEREST_REMINDER = 36,
  C2M_KICK_OFF_BUYER_R2B = 37,
  BM_RESCHEDULE_MEETING_NO_PENDING_MEETING_TO_BUYER = 40,
  BM_RESCHEDULE_MEETING_NO_PENDING_MEETING_TO_EXHIBITOR = 41, 
  BM_RESCHEDULE_MEETING_WITH_PENDING_MEETING_TO_BUYER = 42,
  BM_RESCHEDULE_MEETING_WITH_PENDING_MEETING_TO_EXHIBITOR = 43
}

export enum NotificationType {
  CREATE_MEETING = 'CREATE_MEETING',
  RESCHEDULE_MEETING = 'RESCHEDULE_MEETING',
  ACCEPT_MEETING = 'ACCEPT_MEETING',
  REJECT_MEETING = 'REJECT_MEETING',
  CANCEL_MEETING = 'CANCEL_MEETING',
  AUTO_CANCEL_MEETING = 'AUTO_CANCEL_MEETING',
  BM_CREATE_MEETING = 'BM_CREATE_MEETING',
  BM_CREATE_MEETING_NO_PENDING_MEETING = 'BM_CREATE_MEETING_NO_PENDING_MEETING',
  BM_CREATE_MEETING_WITH_PENDING_MEETING = 'BM_CREATE_MEETING_WITH_PENDING_MEETING',
  RESCHEDULE_BM_MEETING_BY_BUYER_OR_EXHIBITOR = 'RESCHEDULE_BM_MEETING_BY_BUYER_OR_EXHIBITOR',
  CANCEL_BM_MEETING_BY_BUYER_OR_EXHIBITOR = 'CANCEL_BM_MEETING_BY_BUYER_OR_EXHIBITOR',
  CANCEL_BM_MEETING_BY_BM = 'CANCEL_BM_MEETING_BY_BM',
  CANCEL_C2M_MEETING_BY_BM = 'CANCEL_C2M_MEETING_BY_BM',
  MEETING_REMINDER = 'MEETING_REMINDER',
  DAILY_MEETING_SUMMARY = 'DAILY_MEETING_SUMMARY',
  C2M_START_REMINDER = 'C2M_START_REMINDER',
  C2M_KICK_OFF_EXHIBITOR = 'C2M_KICK_OFF_EXHIBITOR',
  C2M_KICK_OFF_BUYER = 'C2M_KICK_OFF_BUYER',
  KOL_EVENT_REMINDER = 'KOL_EVENT_REMINDER',
  SEMINAR_REGISTRATION_SUCCESS = 'SEMINAR_REGISTRATION_SUCCESS',
  SEMINAR_SUMMARY_REMINDER = 'SEMINAR_SUMMARY_REMINDER',
  SEMINAR_ATTENDING_REMINDER = 'SEMINAR_ATTENDING_REMINDER',
  FEEDBACK_FORM_REMINDER = 'FEEDBACK_FORM_REMINDER',
  PLAYBACK_VIDEO_REMINDER = 'PLAYBACK_VIDEO_REMINDER',
  NEW_BM_LIST = 'NEW_BM_LIST',
  UPDATED_BM_LIST = 'UPDATED_BM_LIST',
  NO_RESPONSE_REMINDER = 'NO_RESPONSE_REMINDER',
  NOT_ENOUGH_INTEREST_REMINDER = 'NOT_ENOUGH_INTEREST_REMINDER',
  BM_RESCHEDULE_MEETING = 'BM_RESCHEDULE_MEETING',
  BM_RESCHEDULE_MEETING_NO_PENDING_MEETING = 'BM_RESCHEDULE_MEETING_NO_PENDING_MEETING',
  BM_RESCHEDULE_MEETING_WITH_PENDING_MEETING = 'BM_RESCHEDULE_MEETING_WITH_PENDING_MEETING',
}

export enum ChannelType {
  EMAIL = 'EMAIL',
  WEB_NOTIFICATION = 'WEB_NOTIFICATION',
  PUSH = 'PUSH',
}

export enum ReceiverRole {
  BUYER = 'BUYER',
  EXHIBITOR = 'EXHIBITOR'
}

export enum EmailStatus {
  PENDING = 0,
  SENT = 1,
  NO_NEED_TO_SEND = 2,
  CANNOT_SEND_GET_TEMPLATE_ERROR = 3,
  CANNOT_SEND_GET_FAIRINFO_ERROR = 4,
  CANNOT_SEND_GET_PROFILE_ERROR = 5,
  CANNOT_SEND_GET_COUNTER_PROFILE_ERROR = 6,
  CANNOT_SEND_GET_EMAIL_TYPE_ERROR = 7,
  CANNOT_SEND_GET_CHANNEL_TYPE_ERROR = 8,
  HANDLE_NOTI_ERROR = 9,
  SEND_TO_SNS_ERROR = 10
}

export enum sourceType {
  INHUB = 'intelligence hub',
  FAIRFORM = 'registration form',
  ADMIN = 'admin portal import'
}

export enum userType {
  BUYER = 'Buyer',
  Exhibitor = 'Exhibitor',
  Participant = 'Participant'
}

export enum seminarType {
  ON = 'Online',
  PY = 'Physical',
  PB = 'Playback',
  ALL = 'All'
}

export enum notificationGroup {
  FAIR = 'fair',
  SEMINARS = 'seminar',
  MEETINGS = 'meeting',
}

export enum templateSource {
  DIRECT = 'DIRECT',
  SCHEDULE = 'SCHEDULE',
}