export enum PermissionRefEnum {
    // CBM
    VIEW_CBM_SUMMARY_MANAGEMENT = 90,
    DOWNLOAD_CBM_SUMMARY_REPORT = 91,
    CREATE_AND_EDIT_BM_LIST = 92,
    VIEW_BM_LIST_MANAGEMENT = 93,
    SCHEDULE_MEETING_AT_BM_LIST_MANAGEMENT = 95,
    VIEW_MEETING_MANAGEMENT = 96,
    JOIN_MEETING_AND_SHARE_MEETING = 97,
    CANCEL_MEETING_AT_MEETING_MANAGEMENT = 98,
    RE_SCHEDULE_MEETING = 99,
    GENERAL_SETTING_CONFIG_NOTIFICATION = 100,

    // SEMINAR
    CONFIGURE_LIVE_EVENT_PLAYBACK_LINK = 114
}

export type PermissionRefInterface = Record<PermissionRefEnum, number>;

export type PermissionRefType = keyof PermissionRefInterface;

export const PERMISSION_CBM_SUMMARY = [
    PermissionRefEnum.VIEW_CBM_SUMMARY_MANAGEMENT,
    PermissionRefEnum.SCHEDULE_MEETING_AT_BM_LIST_MANAGEMENT
];

export const PERMISSION_CBM_BUYER = PERMISSION_CBM_SUMMARY;
export const PERMISSION_CBM_EXHIBITOR = PERMISSION_CBM_SUMMARY;

export const PERMISSION_MEETING_LISTING = [
    PermissionRefEnum.VIEW_CBM_SUMMARY_MANAGEMENT,
    PermissionRefEnum.SCHEDULE_MEETING_AT_BM_LIST_MANAGEMENT
];
